server:
  port: 8081

springfox:
  documentation:
    auto-startup: false

spring:
  kafka:
    bootstrap-servers: ${DATA_SYNC_KAFKA_BROKER_URL:localhost:29092}

insolvency:
  delta:
    group-id: insolvency-delta-consumer
    topic: insolvency-delta

logger:
  namespace: insolvency-delta-consumer

api:
  endpoint: ${INSOLVENCY_DATA_API_URL:localhost}
  insolvency-data-api-key: ${INSOLVENCY_DATA_API_KEY:localhost}
  api-url: ${API_URL:localhost}
  internal-api-url: ${INTERNAL_API_URL:localhost}
