server:
  port: 8081

springfox:
  documentation:
    auto-startup: false

spring:
  kafka:
    bootstrap-servers: ${DATA_SYNC_KAFKA_BROKER_URL:localhost:29092}
    listener:
      concurrency: ${INSOLVENCY_DELTA_LISTENER_CONCURRENCY:1}

insolvency:
  delta:
    group-id: ${INSOLVENCY_DELTA_GROUP_ID:insolvency-delta-consumer}
    topic: ${INSOLVENCY_DELTA_TOPIC:insolvency-delta}
    attempts: ${INSOLVENCY_DELTA_ATTEMPTS:4}
    backoff-delay: ${INSOLVENCY_DELTA_BACKOFF_DELAY:100}

logger:
  namespace: insolvency-delta-consumer

api:
  insolvency-data-api-key: ${INSOLVENCY_DATA_API_KEY:localhost}
  api-url: ${INSOLVENCY_DATA_API_URL:localhost}
  internal-api-url: ${INTERNAL_API_URL:localhost}
  mortgage-id-salt: ${MORTGAGE_ID_SALT:testsalt}

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /insolvency-delta-consumer
      path-mapping:
        health: healthcheck
  endpoint:
    health:
      show-details: never
      enabled: true